---
- hosts: idp-servers
  vars:
    aaf_binaries:
      baseurl: https://aaf-binaries.s3-ap-southeast-2.amazonaws.com 
    download:
      jetty:
        baseurl: "{{ aaf_binaries.baseurl }}/jetty"
        version: 9.4.3.v20170317
        sha256sum: d23be69b99c4178a15bda229ef45ca9a0b3b4e2e29445cfcd7e7f50ee22a15bb
      shib_idp:
        baseurl: "{{ aaf_binaries.baseurl }}/shibboleth"
        version: 3.3.1
        sha256sum: 8bd852dcdc7e6729ee645c0374a3c476b152fa24506fb86ffec33dfd190e607c
      mysql_connector:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/Connector-J"
        version: 5.1.35
        sha256sum: fa77909a62363c1aa49ef5ab537ed4affe90a4a6aa5dd1045555b16b2611306d
      dta_ssl:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/jetty9-dta-ssl"
        version: 1.0.0
        sha256sum: 9c62a5999d5adddea905d7caf4220fc073e6033b755f224084cc240dc8d992a6
      commons_dbcp2:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/commons_dbcp2"
        version: 2.1.1
        sha256sum: d6181397b20490aa9b3a793a19c2b75f31af032040d976db1cd97cc2f0ef4379
      commons_pool2:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/commons_pool2"
        version: 2.4.2
        sha256sum: 175ddacc9364b4619ac0fd0fd22acc9d4c372f9099ae5208e8cb72e04a9a872e
      aaf_shib_ext:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/aaf_shib_ext"
        version: 1.1.1
        sha256sum: faf6de1f8be40ec3b3e9cab93ad8ee38a1de77dad51bef36358e28e8d6ae9116
      keystore:
        baseurl: "{{ aaf_binaries.baseurl }}/keystore"
        version: "Unknown"
        sha256sum: ae4185b2f0bb1af00abc6a4502fbfbdc6a90aec65c7bcee08e37a1bc20de5ac1 
      cas_client_core:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/cas_extensions"
        version: 3.3.3
        sha256sum: ed66678bcc81b5407e6379b5a01545991e85dd3950e361a9ed2163679f700c08
      shib_cas_authenticator:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/cas_extensions"
        version: 3.0.0
        sha256sum: 16395533d58990295af2f18f78e4b2a74eb0224ea24bfc655fee8e6b22d0a5b2
    urls:
      jetty:
        url: "{{ download.jetty.baseurl }}/jetty-distribution-{{ download.jetty.version }}.tar.gz"
      shib_idp:
        url: "{{ download.shib_idp.baseurl }}/shibboleth-identity-provider-{{ download.shib_idp.version }}.tar.gz"
      mysql_connector:
        url: "{{ download.mysql_connector.baseurl }}/mysql-connector-java-{{ download.mysql_connector.version }}.tar.gz"
      dta_ssl:
        url: "{{ download.dta_ssl.baseurl }}/jetty9-dta-ssl-{{download.dta_ssl.version}}.jar"
      commons_dbcp2:
        url: "{{ download.commons_dbcp2.baseurl }}/commons-dbcp2-{{ download.commons_dbcp2.version }}-bin.tar.gz"
      commons_pool2:
        url: "{{ download.commons_pool2.baseurl }}/commons-pool2-{{ download.commons_pool2.version }}-bin.tar.gz"
      aaf_shib_ext:
        url: "{{ download.aaf_shib_ext.baseurl }}/aaf-shib-ext-{{ download.aaf_shib_ext.version }}.jar"
      keystore:
        url: "{{ download.keystore.baseurl }}/keystore"
      cas_client_core:
        url: "{{ download.cas_client_core.baseurl }}/cas-client-core-{{ download.cas_client_core.version }}.jar"
      shib_cas_authenticator:
         url: "{{ download.shib_cas_authenticator.baseurl }}/shib-cas-authenticator-{{ download.shib_cas_authenticator.version }}.jar"
    installer:
      root: "{{ install_base }}/shibboleth-idp-installer"
      path: "{{ install_base }}/shibboleth-idp-installer/build"
      repository: "{{ install_base }}/shibboleth-idp-installer/repository"
    jetty:
      root: "{{ install_base }}/jetty"
      home: "{{ install_base }}/jetty/jetty-distribution-{{ download.jetty.version }}"
      base: "{{ install_base }}/shibboleth/jetty"
      current: "{{ install_base }}/jetty/current"
      tmp_directory: "{{ install_base }}/jetty/tmp"
      state_directory: "{{ install_base }}/jetty/tmp"
    shib_idp:
      home_root: "{{ install_base }}/shibboleth/shibboleth-idp"
      home: "{{ install_base }}/shibboleth/shibboleth-idp/shibboleth-idp-{{ download.shib_idp.version }}"
      src_root: "{{ install_base }}/shibboleth/shibboleth-src"
      src: "{{ install_base }}/shibboleth/shibboleth-src/shibboleth-identity-provider-{{ download.shib_idp.version }}"
      keystore_password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/shib_idp_keystore chars=letters,digits length=64') }}"
      cookie_enc_key_password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/cookie_enc_key chars=letters,digits length=64') }}"
      aepst_salt: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/aespt_salt chars=letters,digits length=64') }}"
      targeted_id_salt: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/targeted_id_salt chars=letters,digits length=64') }}"
    db:
      name: idp_db
      username: idp_admin
      password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/mariadb chars=letters,digits length=64') }}"
  tasks:
    - name: 'Create required directories for installer setup'
      file:
        name: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: 0700
      with_items:
        - '{{ installer.root }}'
        - '{{ installer.path }}'

    - name: 'Update yum packages (yum -y update)'
      yum: name=* state=latest
      when: ((server_patch is undefined) or (server_patch is none) or (server_patch=="true"))

    - name: 'Set SELinux to permissive mode'
      selinux:
        policy: targeted
        state: permissive

    - name: 'Install required packages'
      yum: pkg={{ item }} state=installed
      with_items:
        - httpd
        - mod_ssl
        - mod_ldap
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        - mariadb-server
        - mariadb-devel
        - mariadb
        - MySQL-python
        - ntp
        - expect

    - name: 'Enable NTP service'
      service: name=ntpd state=started enabled=yes

    - include: tasks/jetty.yml
    - include: tasks/db.yml
    - include: tasks/idp.yml
    - include: tasks/apache.yml
    - include: tasks/firewalld.yml

  handlers:
    - name: Restart idp
      service:
        name: idp
        state: restarted
    - name: Restart Apache
      service:
        name: httpd
        state: restarted

