---
- name: 'Set shared facts'
  set_fact:
    jetty_dist_archive_path='{{ installer.path }}/jetty-distribution-{{ download.jetty.version }}.tar.gz'

- name: 'Create jetty user'
  user: name=jetty

- name: 'Create jetty root'
  file:
    path: '{{ jetty.root }}'
    owner: root
    group: jetty
    state: directory
    mode: 0750

- name: 'Download jetty distribution'
  get_url:
    url: '{{ urls.jetty.url }}'
    dest: '{{ jetty_dist_archive_path }}'
    sha256sum: '{{ download.jetty.sha256sum }}'

- name: 'Extract jetty distribution'
  shell: >
    umask 0027;
    tar zx -C {{ jetty.root }} -f {{ jetty_dist_archive_path }} --no-same-permissions;
    chgrp -R jetty {{ jetty.home }}
    creates={{ jetty.home }}

- name: 'Remove demo-base'
  file:
    path: '{{ jetty.home }}/demo-base'
    state: absent

- name: 'Symlink jetty to installed distribution'
  file:
    name: '{{ jetty.current }}'
    src: '{{ jetty.home }}'
    owner: root
    group: root
    state: link
    force: yes

- name: 'Create directories required for JETTY_BASE'
  file:
    name: '{{ item }}'
    state: directory
    owner: root
    group: jetty
    mode: 0750
  with_items:
    - '{{ jetty.base }}'
    - '{{ jetty.base }}/modules'
    - '{{ jetty.base }}/etc'
    - '{{ jetty.base }}/webapps'
    - '{{ jetty.base }}/lib'
    - '{{ jetty.base }}/lib/ext'
    - '{{ jetty.base }}/resources'
    - '{{ jetty.base }}/start.d'

- name: 'Set backchannel.mod'
  template:
    dest: '{{ jetty.base }}/modules/backchannel.mod'
    src: 'templates/jetty/backchannel.mod'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set http.mod'
  template:
    dest: '{{ jetty.base }}/modules/http.mod'
    src: 'templates/jetty/http.mod'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set https.mod'
  template:
    dest: '{{ jetty.base }}/modules/https.mod'
    src: 'templates/jetty/https.mod'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set ssl.mod'
  template:
    dest: '{{ jetty.base }}/modules/ssl.mod'
    src: 'templates/jetty/ssl.mod'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set backchannel.ini'
  template:
    dest: '{{ jetty.base }}/start.d/backchannel.ini'
    src: 'templates/jetty/backchannel.ini'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set http.ini'
  template:
    dest: '{{ jetty.base }}/start.d/http.ini'
    src: 'templates/jetty/http.ini'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set https.ini'
  template:
    dest: '{{ jetty.base }}/start.d/https.ini'
    src: 'templates/jetty/https.ini'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set ssl.ini'
  template:
    dest: '{{ jetty.base }}/start.d/ssl.ini'
    src: 'templates/jetty/ssl.ini'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set console-capture.ini'
  template:
    dest: '{{ jetty.base }}/start.d/console-capture.ini'
    src: 'templates/jetty/console-capture.ini'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set jetty-backchannel.xml'
  template:
    dest: '{{ jetty.base }}/etc/jetty-backchannel.xml'
    src: 'templates/jetty/jetty-backchannel.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set jetty.xml'
  template:
    dest: '{{ jetty.home }}/etc/jetty.xml'
    src: 'templates/jetty/jetty.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set jetty-https.xml'
  template:
    dest: '{{ jetty.base }}/etc/jetty-https.xml'
    src: 'templates/jetty/jetty-https.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set jetty-ssl.xml'
  template:
    dest: '{{ jetty.base }}/etc/jetty-ssl.xml'
    src: 'templates/jetty/jetty-ssl.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set jetty-requestlog logback configuration'
  template:
    dest: '{{ jetty.home }}/etc/jetty-requestlog.xml'
    src: 'templates/jetty/jetty-requestlog.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set jetty-logging logback configuration'
  template:
    dest: '{{ jetty.home }}/etc/jetty-logging.xml'
    src: 'templates/jetty/jetty-logging.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set permissions on jetty directory'
  file:
    path: '{{ jetty.home }}'
    owner: root
    group: jetty
    mode: 0750
    state: directory

- name: 'Create jetty state directory'
  file:
    path: '{{ jetty.state_directory }}'
    owner: jetty
    group: jetty
    state: directory
    mode: 0700

- name: 'Create a tmp directory for jetty'
  file:
    path: '{{ jetty.tmp_directory }}'
    owner: jetty
    group: jetty
    state: directory
    mode: 0700

- name: 'Set permissions on jetty files'
  file:
    path: '{{ item }}'
    owner: root
    group: jetty
    mode: 0640
  with_items:
  - '{{ jetty.home }}/license-eplv10-aslv20.html'
  - '{{ jetty.home }}/notice.html'
  - '{{ jetty.home }}/start.ini'
  - '{{ jetty.home }}/start.jar'
  - '{{ jetty.home }}/VERSION.txt'
  - '{{ jetty.home }}/README.TXT'

  
- name: 'Set permissions on jetty directory'
  file:
    path: '{{ item }}'
    owner: root
    group: jetty
    mode: 0750
  with_items:
  - '{{ jetty.home }}'
  - '{{ jetty.home }}/modules'
  - '{{ jetty.home }}/resources'
  - '{{ jetty.home }}/etc'
  - '{{ jetty.home }}/lib'
  - '{{ jetty.home }}/webapps'
  - '{{ jetty.home }}/bin'

- name: 'Set executable files for jetty'
  file:
    path: '{{ item }}'
    owner: root
    group: jetty
    mode: 0750
  with_items:
  - '{{ jetty.home }}/bin/jetty.sh'

