#!/bin/bash

uri="https://aaf-build-artifacts.s3-ap-southeast-2.amazonaws.com/rapid-idp-migrate/rapid-idp-migrate.jar"
file="rapid-idp-migrate.jar"
dir=`dirname "$0"`

# Check if the jar file has ever been downloaded
if test -e "$dir/$file"
then zflag=(-z "$dir/$file" -Ss) # Existing file. Check if newer exists.
else zflag=() # Never existed. Show download progress (lack of -Ss).
fi

curl -o "$dir/$file" "${zflag[@]}" "$uri"

java -jar ${dir}/rapid-idp-migrate.jar $*
